#Configuration for clouddev development environment
spring:
  profile: clouddev
  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
  cloud:
    discovery:
      enabled: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false