server:
  port: 4100

spring:
  datasource:
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL

  cloud:
    discovery:
      enabled: true
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500
            