server:
  port: 4101

spring:
  cloud:
    discovery:
      enabled: true
      
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    
  #hibernate.dialect=org.hibernate.dialect.H2Dialect
  hibernate:
    dialect: org.hibernate.dialect.H2Dialect