server:
  port: 4100

spring:
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    enabled: true
    registerWithEureka: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registration:
      enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500
            