server:
  port: 4000

spring:
  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
eureka:
  client:
    enabled: false
    registerWithEureka: false
    register-with-eureka: false
    registration:
      enabled: false
